version: '3.1'
services:
    web:
      image: odoo:18.0
      ports:
        - "8069:8069"
      volumes:
#        - /home/ubuntu/efs:/var/lib/odoo
        - odoo-web-data:/var/lib/odoo
#        - ./config:/etc/odoo
      environment:
        - HOST=rds-db.cs4cdisa3een.ap-southeast-1.rds.amazonaws.com
        - PORT=5432
        - USER=postgres
        - PASSWORD=InnovixS2024

volumes:
  odoo-web-data: