version: '3.1'
services:
    web:
      build:
        context: .
      ports:
        - "8069:8069"
      volumes:
        - /home/ubuntu/efs:/var/lib/odoo
        - ./config:/etc/odoo
      environment:
        - HOST=rds-testing.cs4cdisa3een.ap-southeast-1.rds.amazonaws.com
        - PORT=5432
        - USER=ubuntu
        - PASSWORD=InnovixS2024
      # Resource limits
      deploy:
        resources:
          limits:
            cpus: "2.0"    # Limit to 2 CPUs
            memory: 3G     # Limit to 3GB RAM
          reservations:
            cpus: "1.0"    # Reserve 1 CPU
            memory: 2G     # Reserve 2GB RAM

    nginx:
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - web