version: '3.1'
services:
    web:
      build:
        context: .
#      image: odoo:18.0
      ports:
        - "8069:8069"
      volumes:
        - /home/ubuntu/efs:/var/lib/odoo
#        - odoo-web-data:/var/lib/odoo
        - ./config:/etc/odoo
      environment:
        - HOST=rds-db.cs4cdisa3een.ap-southeast-1.rds.amazonaws.com
        - PORT=5432
        - USER=odoo
        - PASSWORD=odoo

#    nginx:
#      image: nginx:latest
#      ports:
#        - "80:80"
#      volumes:
#        - ./nginx.conf:/etc/nginx/nginx.conf:ro
#      depends_on:
#        - web
volumes:
  odoo-web-data: