version: '3.1'
services:
    web:
      build:
        context: .
      ports:
        - "8069:8069"
      volumes:
        - /home/ubuntu/efs:/var/lib/odoo
        - ./config:/etc/odoo
      environment:
        - HOST=rds-db.cs4cdisa3een.ap-southeast-1.rds.amazonaws.com
        - PORT=5432
        - USER=odoo
        - PASSWORD=odoo
volumes:
  odoo-web-data: