version: '3.1'
services:
    web:
      build:
        context: .
#      ports:
#        - "8069:8069"
      volumes:
        - /home/ubuntu/s3-drive/odoo-web-data:/var/lib/odoo
        - ./config:/etc/odoo
      environment:
        - HOST=rds-testing.cs4cdisa3een.ap-southeast-1.rds.amazonaws.com
        - PORT=5432
        - USER=ubuntu
        - PASSWORD=InnovixS2024

    nginx:
      image: nginx:latest
      ports:
        - "8090:80"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - web